export interface EventItem {
    id: number;
    title: string;
    type: string;
    category: string;
    status: 'Proximos' | 'EnCurso' | 'Pasados';
    statusLabel: string;
    statusColor: string;
    date: string;
    time: string;
    location: string;
    organizer: string;
    description: string;
    image: string;
    fbLink: string;
    isProyeccionSocial: boolean;
}

export const eventsList: EventItem[] = [
    {
        id: 1,
        title: 'Inauguración del Estadio Monumental de la UNA Puno',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Proximos',
        statusLabel: 'Próximo',
        statusColor: 'bg-indigo-600',
        date: '20 de Junio',
        time: '09:00 AM',
        location: 'Estadio Monumental UNA Puno',
        organizer: 'Rectorado y Dirección de Extensión Cultural',
        description: 'Inauguración del mejor escenario deportivo de Puno, con partidos clásicos de leyendas de Universitario y Alianza Lima.',
        image: 'https://cdn.phototourl.com/free/2026-07-09-0644787f-0ea3-4f10-a794-2d3a5dbb3972.png',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 2,
        title: 'Capacitación de Brigadas Ambientales y Primeros Auxilios',
        type: 'Campaña Social',
        category: 'Proyección Social',
        status: 'Proximos',
        statusLabel: 'Próximo',
        statusColor: 'bg-indigo-600',
        date: '21 de Abril',
        time: '11:00 AM',
        location: 'Auditorio Magno',
        organizer: 'Dirección de Proyección Social y Extensión Cultural',
        description: 'Convocatoria y capacitación oficial de brigadistas de cara al XI Concurso de Sikuris UNA Puno.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 3,
        title: 'La UNA Puno por la Inserción Laboral',
        type: 'Académico',
        category: 'Proyección Social',
        status: 'Proximos',
        statusLabel: 'Próximo',
        statusColor: 'bg-indigo-600',
        date: '17 de Abril',
        time: '09:00 AM',
        location: 'Auditorio de Ingeniería',
        organizer: 'Sub Unidad de Seguimiento al Graduado',
        description: 'Talleres de entrevista personal, elaboración de CV y presentación de bolsa de empleo para egresados.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 4,
        title: 'Difusión de Políticas Ambientales – Inducción de Arte y Danza',
        type: 'Ambiental',
        category: 'Proyección Social',
        status: 'Proximos',
        statusLabel: 'Próximo',
        statusColor: 'bg-indigo-600',
        date: '9 de Abril',
        time: '10:00 AM',
        location: 'Escuela Profesional de Arte, Programa de Danza',
        organizer: 'Sub Unidad de Gestión Ambiental - DPESEC',
        description: 'Sesión de inducción para nuevos ingresantes con el fin de sensibilizar en la conservación del entorno y el desarrollo sostenible institucional.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 5,
        title: 'Tuna Universitaria UNA Puno',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Proximos',
        statusLabel: 'Próximo',
        statusColor: 'bg-indigo-600',
        date: '10 de Abril',
        time: '04:00 PM',
        location: 'Ciudad Universitaria',
        organizer: 'Dirección de Proyección Social y Extensión Cultural',
        description: 'Convocatoria abierta para ser parte de la tradicional Tuna Universitaria UNA Puno, compartiendo hermandad, música y tradición.',
        image: 'https://cdn.phototourl.com/free/2026-07-09-0086b13b-6bd6-407c-8e84-964f82c578d1.png',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 6,
        title: 'Gran Jornada de Limpieza y Conservación del Bosque Universitario',
        type: 'Ambiental',
        category: 'Voluntariado Universitario',
        status: 'EnCurso',
        statusLabel: 'En Curso',
        statusColor: 'bg-emerald-600',
        date: '1 de Junio',
        time: '07:30 AM',
        location: 'Bosque Universitario UNA',
        organizer: 'Sub Unidad de Gestión Ambiental',
        description: 'Gran jornada ecológica bajo el lema "Vidas que cuidan vidas" para conservar nuestro entorno verde.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 7,
        title: 'IV Jornada de Limpieza del Bosque Universitario',
        type: 'Ambiental',
        category: 'Voluntariado Universitario',
        status: 'EnCurso',
        statusLabel: 'En Curso',
        statusColor: 'bg-emerald-600',
        date: '4 de Junio',
        time: '08:00 AM',
        location: 'Bosque Universitario UNA',
        organizer: 'Sub Unidad de Gestión Ambiental - DPESEC',
        description: 'Éxito en la jornada organizada por la Sub Unidad de Gestión Ambiental con estudiantes y docentes en el Día Mundial del Ambiente.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 8,
        title: 'Grabando Voces del Quechua de Puno',
        type: 'Campaña Social',
        category: 'Voluntariado Universitario',
        status: 'EnCurso',
        statusLabel: 'En Curso',
        statusColor: 'bg-emerald-600',
        date: '26 de Enero',
        time: 'Flexible',
        location: 'Provincias de Puno',
        organizer: 'Mozilla Foundation y DPESEC',
        description: 'Voluntariado para documentar y salvaguardar el quechua como parte del patrimonio lingüístico de nuestra región.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 9,
        title: 'Premiación a los Ganadores del XI Concurso de Sikuris UNA',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '29 de Abril',
        time: '10:00 AM',
        location: 'Estadio Monumental',
        organizer: 'Dirección de Proyección Social y Extensión Cultural',
        description: 'Reconocimiento y premiación del XI Concurso de Sikuris coronando a Ingeniería Civil como ganador absoluto.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 10,
        title: 'II Concurso de Nacimientos: Cristo nace en la Universidad',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '22 de Diciembre',
        time: '11:00 AM',
        location: 'Ciudad Universitaria',
        organizer: 'Dirección de Proyección Social',
        description: 'Concurso de nacimientos uniendo talento, fe, identidad y espíritu navideño en la comunidad universitaria.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 11,
        title: '65 Aniversario de Reapertura Institucional UNA',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '29 de Abril',
        time: '09:00 AM',
        location: 'Ciudad Universitaria',
        organizer: 'Rectorado UNA Puno',
        description: 'Celebrando 65 años de historia, esfuerzo y compromiso de la Universidad Nacional del Altiplano formando profesionales.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 12,
        title: 'Reconocimiento a Brigadas Ambientales y de Primeros Auxilios',
        type: 'Campaña Social',
        category: 'Voluntariado Universitario',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '29 de Abril',
        time: '11:00 AM',
        location: 'Rectorado UNA Puno',
        organizer: 'Sub Unidad de Gestión Ambiental - DPESEC',
        description: 'Reconocimiento a brigadistas universitarios por su dedicada labor en el XI Concurso de Sikuris UNA Puno.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 13,
        title: 'Compromiso Institucional y Reforestación Urbana',
        type: 'Ambiental',
        category: 'Proyección Social',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '28 de Enero',
        time: '08:00 AM',
        location: 'Zonas urbanas de Puno',
        organizer: 'Sub Unidad de Gestión Ambiental y EP Ingeniería Agrícola',
        description: 'Jornada de reforestación para la recuperación de áreas verdes y la mitigación del cambio climático en la región.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 14,
        title: 'Cultura y Compromiso Ambiental en la Candelaria',
        type: 'Ambiental',
        category: 'Extensión Cultural',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '31 de Enero',
        time: '08:00 AM',
        location: 'LXI Concurso de Danzas Originarias',
        organizer: 'Sub Unidad de Gestión Ambiental - DPESEC',
        description: 'Brigadas Ambientales concientizando sobre el manejo responsable de residuos durante la Festividad de la Candelaria.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    },
    {
        id: 15,
        title: 'Festival Artístico de Música y Danza',
        type: 'Cultural',
        category: 'Extensión Cultural',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '17 de Diciembre',
        time: '03:00 PM',
        location: 'Ciudad Universitaria',
        organizer: 'Dirección de Proyección Cultural de la UNA Puno',
        description: 'Importante festival artístico con danzas originarias y trajes de luces, promoviendo valores de integración y trabajo en equipo.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: false
    },
    {
        id: 16,
        title: 'Jornada: Estrategias de Estudio y Orientación Vocacional',
        type: 'Académico',
        category: 'Proyección Social',
        status: 'Pasados',
        statusLabel: 'Finalizado',
        statusColor: 'bg-neutral-500',
        date: '17 de Diciembre',
        time: '09:00 AM',
        location: 'Juliaca - Colegio José Olaya Balandra',
        organizer: 'Sub Unidad de Extensión Universitaria y Proyección Social',
        description: 'Visita guiada para estudiantes de Juliaca a laboratorios universitarios promoviendo la educación superior.',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        fbLink: 'https://www.facebook.com/ProyeccionSocialUNAPuno',
        isProyeccionSocial: true
    }
];
